name: Windows (dotnet build and test)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  os-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
            7.0.x
            6.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/CSharp/Blazor/EasyMicroservices.UI.Ordering.Blazor.sln
        run: dotnet restore ./src/CSharp/Cores/EasyMicroservices.UI.Ordering.Core.sln
      - name: Build
        run: dotnet build ./src/CSharp/Blazor/EasyMicroservices.UI.Ordering.Blazor.sln --no-restore
        run: dotnet build ./src/CSharp/Cores/EasyMicroservices.UI.Ordering.Core.sln --no-restore
      - name: Test
        run: dotnet test ./src/CSharp/Blazor/EasyMicroservices.UI.Ordering.Blazor.sln --no-build --verbosity normal
        run: dotnet test ./src/CSharp/Cores/EasyMicroservices.UI.Ordering.Core.sln --no-build --verbosity normal
